package com.assign3;

import java.io.IOException;
import java.io.PrintWriter;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/RegisterServlet")
public class RegisterServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    // Database connection method
    private Connection getConnection() throws Exception {

        String url = "jdbc:mysql://localhost:3306/assign3db";
        String username = "nets1038_w2026_mv";
        String password = "class123";

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection(url, username, password);

        return conn;
    }

    // Method to hash password using MD5
    private String md5Hash(String password) throws Exception {

        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(password.getBytes());

        byte[] bytes = md.digest();

        StringBuilder sb = new StringBuilder();

        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }

        return sb.toString();
    }

    // Insert method (PreparedStatement required by assignment)
    private void insertUser(String username, String passwordHash, String mobile, String email) throws Exception {

        Connection conn = getConnection();

        String sql = "INSERT INTO users (userName, passwordHash, mobileNumber, emailId) VALUES (?, ?, ?, ?)";

        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, username);
        ps.setString(2, passwordHash);
        ps.setString(3, mobile);
        ps.setString(4, email);

        ps.executeUpdate();

        conn.close();
    }

    // Select method (required second method)
    private void selectUsers(HttpServletResponse response) throws Exception {

        Connection conn = getConnection();

        String sql = "SELECT * FROM users";

        PreparedStatement ps = conn.prepareStatement(sql);

        ResultSet rs = ps.executeQuery();

        PrintWriter out = response.getWriter();

        while (rs.next()) {

            out.println(rs.getString("userName") + " | "
                    + rs.getString("mobileNumber") + " | "
                    + rs.getString("emailId") + "<br>");

        }

        conn.close();
    }

    // Handles form submission
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        try {

            String username = request.getParameter("username");
            String password = request.getParameter("password");
            String mobile = request.getParameter("mobile");
            String email = request.getParameter("email");

            String hashedPassword = md5Hash(password);

            insertUser(username, hashedPassword, mobile, email);

            response.getWriter().println("Your HashCode Generated by MD5 is: " + hashedPassword + "<br><br>");

            selectUsers(response);

        } catch (Exception e) {

            e.printStackTrace();
        }
    }
}